### ISSUE TITLE
Support for Swift Package Manager and XCframeworks

### ISSUE THREAD

**Issue by andreyz** [UserLeap/userleap-ios-sdk-releases#14]
It's about time to offer SDKs as SPM and XCframeworks on iOS platform.

[WWDC: Binary Frameworks in Swift](https://developer.apple.com/videos/play/wwdc2019/416/)
Please note of [this SPM issue with a workaround](https://steipete.com/posts/couldnt-irgen-expression/).

**Comment by helloandrewpark** [comment]
Appreciate the workaround link, will get back to you on this

**Comment by brettohland** [comment]
I second this request.

**Comment by samueljamesbell** [comment]
Me too - would love to use SPM for UserLeap

**Comment by kristersj** [comment]
Hi, is there any progress on this?

**Comment by helloandrewpark** [comment]
we have this prioritized for this quarter. Hoping to get this out late december

**Comment by samueljamesbell** [comment]
Hi @helloandrewpark, thanks for prioritizing this ticket! Just wondering if you're still planning on late December?

**Comment by helloandrewpark** [comment]
@samueljamesbell yep!

**Comment by samueljamesbell** [comment]
Fantastic, thanks for confirming!!!!

**Comment by gongstr** [comment]
@samueljamesbell `4.5.0` supports xcframeworks now. please try it out and let us know if you have any suggestions.

**Comment by samueljamesbell** [comment]
Hello @gongstr @helloandrewpark 

Thanks so much for releasing v 4.5.0. 

I've tried adding `https://github.com/UserLeap/userleap-ios-sdk-releases/` using SPM, but it fails due to `no Package.swift manifest`. 

Do you have any suggestions?

Thanks,
Sam

**Comment by gongstr** [comment]
Hi @samueljamesbell  sorry about the confusion. For now the sdk can be installed using carthage or cocoapods as xcframework. SPM support is coming soon.

**Comment by samueljamesbell** [comment]
Thanks @gongstr. Do you have an ETA on SPM support?

**Comment by gongstr** [comment]
SPM support is ready as well. In order to install using SPM, you need to star the repo. Then please install the package from main branch like so (dependency by version doesn't seem to work, we'll file a radar and follow up but installing from main seems to work for now)
![image](https://user-images.githubusercontent.com/73458232/146864812-6b993dfe-b3c6-451d-9a11-48ae0c138c08.png)

**Comment by samueljamesbell** [comment]
Thanks @gongstr - worked like a charm.

**Comment by bbauman1** [comment]
@gongstr Do you have any advice on this build error? I'm only seeing it when building in Circle CI and not locally. This is happening when moving from cocoapods to SPM.

```
Failed to clone repository https://github.com/UserLeap/userleap-ios-sdk-releases/:
    Cloning into bare repository '/Users/redacted/Library/Developer/Xcode/DerivedData/redacted/SourcePackages/repositories/userleap-ios-sdk-releases-2bcd4329'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
```

**Comment by gongstr** [comment]
interesting, I'll look into this.
