### ISSUE TITLE
Multiple invocations of callback in .track() function

### ISSUE THREAD

**Issue by ninjz** [UserLeap/userleap-ios-sdk-releases#21]
When calling .track() I'm receiving multiple calls to the callback closure. This results in me having to keep some sort of state to manage receiving only the first value so I don't end up presenting multiple survey modals.

**Comment by helloandrewpark** [comment]
Hey @ninjz , thank you for submitting this issue. That's strange, I don't see how we could be calling it multiple times for a single `track()` call and I'm unable to reproduce. Would you be able to share a small project that reproduces this bug?
