### ISSUE TITLE
Not available for armv7-apple-ios

### ISSUE THREAD

**Issue by bakua** [UserLeap/userleap-ios-sdk-releases#26]
Hello, I am trying to buid a release version of my app with imported UserLeap but it seems to not to include armv7 libs.

I get the following error:
```
could not find module 'UserLeapKit' for target 'armv7-apple-ios'; found:
    i386, x86_64-apple-ios-simulator, arm64, x86_64, i386-apple-ios-simulator, arm64-apple-ios
```

**Comment by abhishek1214** [comment]
Hey I am facing same issue. Any updates on this?

`Could not find module 'UserLeapKit' for target 'armv7-apple-ios'; found: i386, x86_64-apple-ios-simulator, arm64, x86_64, i386-apple-ios-simulator, arm64-apple-ios`

**Comment by helloandrewpark** [comment]
hey @bakua @abhishek1214, unfortunately this SDK is written in Swift 5.3 so we can't support armv7. I'm not aware of any workarounds for this limitation but please share if you know of any

**Comment by bakua** [comment]
I don't know either. I looked around a little bit and armv7 are used only by devices up to iphone 4s, which is prety relic by now. so I am ok with not supporting it.

However, I haven't found a way how to remove support for armv7 architecture for ios flutter project. Nothing works for me. @helloandrewpark would you be able to advise how to exclude it correctly please?

**Comment by helloandrewpark** [comment]
@bakua  Unfortunately i'm not too familiar with flutter.. the only thing i'm aware of is setting the `Excluded Architectures` configuration in the project settings

**Comment by bakua** [comment]
Yes I have tried that setting for my Runner project, but it didn't help so I was lost.
However, setting it also on Pods project did the trick for some reason.

Thank you
