### ISSUE TITLE
Xcode 13 beta building issues

### ISSUE THREAD

**Issue by glm4** [UserLeap/userleap-ios-sdk-releases#29]
I have tested with versions 4.2.0 and 4.3.0 of the framework and on Xcode 13 with the command line tools for 13.0 and 12.5.
I am getting this error at build time:

<img width="959" alt="Screen Shot 2021-06-23 at 16 23 57" src="https://user-images.githubusercontent.com/12735630/123156573-d6667880-d43f-11eb-95b1-a2f3a90e9d18.png">

Please advice. Thanks!

**Comment by helloandrewpark** [comment]
Hey @glm4! thanks for surfacing this, we'll have a fix uploaded this week

**Comment by helloandrewpark** [comment]
Please checkout https://github.com/UserLeap/userleap-ios-sdk-releases/releases/tag/4.3.0-beta
