### ISSUE TITLE
M1 Simulator Support

### ISSUE THREAD

**Issue by samus** [UserLeap/userleap-ios-sdk-releases#45]
The SDK doesn't include support for the iOS Arm64 simulator.  After adding version 4.4.2 to my Podfile, I'm no longer able to create simulator builds.  Without simulator builds I'm unable to edit any SwiftUI screens.  A workaround for this is to run Xcode in Rosetta mode but the swiftui previews only work sporadically and cause great frustration within the dev team.

**Comment by gongstr** [comment]
4.4.3 has released. I added back the arm64 support. Please update and let us know

**Comment by samus** [comment]
Hello, this does not fix the issue for me.  Attached is a simple project to reproduce the issue.  Commenting out all of the pods and running `pod update` causes the `Excluded Architectures` setting under the Test target to be empty.  Uncommenting the `pod 'UserLeapKit', '~>4.4.3'` line and re-running `pod update` causes the return of the `arm64` entry to the Excluded Architectures setting for simulators.  I have verified in the Podfile.lock that it is indeed pulling version 4.4.3 and not a different one.  Cocoapods is version 1.11.
[M1 Simulator Test.zip](https://github.com/UserLeap/userleap-ios-sdk-releases/files/7621007/M1.Simulator.Test.zip)

**Comment by gongstr** [comment]
Thanks for the example.. Let me see why this is. We removed arm64 from excluded arch already.

**Comment by ninjz** [comment]
I'm also getting this error when trying to build for the simulator on my new M1 machine:

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/.../Pods/UserLeapKit/UserLeapKit.framework/UserLeapKit' for architecture arm64
```

**Comment by gongstr** [comment]
On 4.4.3 or 4.4.2, could you try adding this to the build setting for your app? 
![image](https://user-images.githubusercontent.com/73458232/145453359-abf1de64-63c6-4d28-a4c0-c75241ad370e.png)

**Comment by samus** [comment]
That is put in there by Cocoapods as soon as the UserLeapKit pod is included and the reason that M1 simulator builds fail.
<img width="1116" alt="Screen Shot 2021-12-10 at 6 21 26 PM" src="https://user-images.githubusercontent.com/111197/145653299-cd881514-c4f1-42de-9b51-e52e4a380db3.png">

**Comment by gongstr** [comment]
Some clarifying context on what I tried:
For version `4.4.2` and `4.4.3`, the sdk has the arm64 in excluded architecture build setting, and I was able to build a test app on simulator on m1 if I add the arm64 in excluded architecture for the test app
For version `4.4.4`, the sdk removed the arm64 in excluded architecture build setting, and I wasn't able to build the test app successfully on m1. 
But sounds like this is not the case for you. So I'm curious if you have any other error messages.
Could you try out `4.4.4`? We had a version issue with `4.4.3` and it wasn't removing the arm64 setting properly. And `4.4.4` fixed that issue. And if you still can't build on simulator could I have the error message?

**Comment by gongstr** [comment]
@ninjz @samus have you guys had a chance to try the new release? Please let us know if you run into more issues.

**Comment by samus** [comment]
I finally had a chance to try it out today.  It is working fine for me now with the XCFramework.  Thank you for taking care of this.  I'm now able to run Xcode in native mode.
